# _config.yml

# Site settings
title: "Toronto Pro Moving"
description: "Toronto's trusted movers for residential, commercial, and specialty relocations."
url: "https://torontopromoving.com"
baseurl: ""

# Theming
theme:
  font:
    family: "Inter, sans-serif"
    weights: ["400", "600", "700"]

  border_radius_1: "5px"
  border_radius_2: "5px"

  colors:
    # Backgrounds

    #nav
    nav_bg: "#005bbd"
    nav_links: "#ffffff"
    nav_links_hover: "#dce9f8"


    bg_main:      "#ffffff"      # Soft blue-tinted white
    bg_secondary: "#e6f0fa"      # Very light cool blue
    bg_accent:    "#dce9f8"      # Light blue
    bg_light:     "#ffffff"
    surface:      "#ffffff"

    # Primary / Accent
    primary:       "#005bbd"     # Deep blue
    primary_light: "#4d8fe8"     # Lighter blue
    primary_dark:  "#003f8a"     # Dark navy blue

    # Secondary
    secondary:       "#00a6ed"   # Cyan/bright blue accent
    secondary_light: "#66cfff"
    secondary_dark:  "#007bb8"

    # Text
    text:         "#1a1a1a"      # Near black
    text_light:   "#4d4d4d"
    text_dark_bg: "#ffffff"

    # Accents & states
    accent:       "#007bff"
    accent_dark:  "#0056b3"
    border:       "#4d8fe8"
    error:        "#ff4d4f"
    delete:       "#ff4d4f"

    on_primary:   "#ffffff"

# Hero section
hero:
  description: >
    Reliable. Efficient. Professional. Toronto Pro Moving is your local expert in residential, commercial, and specialty moving services.
  image: "/assets/images/hero-toronto.jpg"

# About / Features section
about:
  title: "Why Choose Toronto Pro Moving?"
  features:
    - title: "Local Expertise"
      text: "Born and bred in Toronto — we know every corner of the city."
    - title: "Transparent Pricing"
      text: "No hidden fees. Ever. We offer fair, upfront pricing on every move."
    - title: "Fast & Secure"
      text: "We handle your belongings with care, speed, and professionalism."
    - title: "Fully Licensed & Insured"
      text: "We provide peace of mind by meeting the highest industry standards."

# Call-to-Action blocks
cta-1:
  title: "Ready to Move?"
  text: "Get your free quote today and let Toronto Pro Moving take the stress out of your next move."
  button: "Get a Quote"

cta-2:
  title: "Questions? Let's Talk."
  button: "Contact Us"

# Quote form
quote:
  submission_url: "https://shadow-seagull-4892.twil.io/submit_quote_request"
  job_types:
    - label: "Residential Moving"
      options:
        - "Studio Apartment"
        - "1 Bedroom Apartment"
        - "2 Bedroom Home"
        - "3+ Bedroom Home"
    - label: "Specialty Services"
      options:
        - "Piano Moving"
        - "Furniture Assembly"
        - "Packing & Unpacking"
        - "Storage Solutions"
    - label: "Commercial"
      options:
        - "Office Moving"
        - "Retail Relocation"
    - label: "Other"
      options:
        - "Custom Request"

# Contact info
phone:
  ie64: "+14165551234"
  display: "(416) 555-1234"
  twilio_account_sid: "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
email: "info@torontopromoving.com"

address:
  - "456 Spadina Ave"
  - "Toronto, ON M5S 2G8"

hours:
  - "Mon–Fri: 8 AM – 8 PM"
  - "Sat–Sun: 9 AM – 6 PM"

# Navigation links
nav_links:
  - title: "Services"
    url: "#faq"
  - title: "Locations"
    url: "#locations"
  - title: "Moving Tips"
    url: "#faq"
  - title: "About Us"
    url: "#about"

# Locations map & data
locations:
  map_theme_url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_marker_icon: "fa-solid fa-map-pin"
  map_marker_color: "#005bbd"
  location_data:
    - name: "Downtown Toronto"
      coordinates: "43.6532, -79.3832"
    - name: "Etobicoke"
      coordinates: "43.6205, -79.5132"
    - name: "Scarborough"
      coordinates: "43.7767, -79.2318"
    - name: "North York"
      coordinates: "43.7615, -79.4111"
    - name: "Mississauga"
      coordinates: "43.5890, -79.6441"

# FAQ & Moving Tips
faq_title: "Your Moving Questions Answered"
faq:
  - question: "Do you provide packing materials?"
    answer: "Yes, we offer a range of packing supplies and can even pack for you!"
  - question: "Are you insured?"
    answer: "Absolutely. We are fully licensed and insured for all residential and commercial moves."
  - question: "Can I book last-minute?"
    answer: "We accommodate last-minute requests when availability allows. Contact us for details."
  - question: "Do you move outside of Toronto?"
    answer: "Yes, we also service the GTA including Mississauga, Vaughan, and more."

# Testimonials
testimonials:
  - text: "They were punctual, professional, and very careful with my stuff. Best movers in Toronto!"
    author: "— Alex R."
    location: "Downtown Toronto"
    rating: 5
  - text: "Moved my piano with precision and no fuss. Highly recommend."
    author: "— Priya S."
    location: "Scarborough"
    rating: 4.5
  - text: "Booking was easy and the team was friendly. A smooth experience all around."
    author: "— Marcus J."
    location: "Etobicoke"
    rating: 5
